### ISSUE TITLE
Unable to use teams

### ISSUE THREAD

**Issue by MarkHarrisMedia** [DrexHD/OrderedPlayerList#10]
![image](https://github.com/user-attachments/assets/9e369af7-7ecf-413c-9cf6-5098aa8ad827)

**Comment by DrexHD** [comment]
This is unfortunately a limitation in minecraft. All versions in 1.21.2 and higher will not have this problem. The teams do still exist, but the client is confused, because this mod needs to use some fake team trickery to order players. You can still execute all commands like you would without the mod, but command suggestions are messed up!
